"""drop_chat_and_message

Revision ID: bb71d4b03533
Revises: dfb4bb64a3e8
Create Date: 2025-12-31 14:54:47.400210

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb71d4b03533"
down_revision = 'dfb4bb64a3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('root_message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('chats_pkey'))
    )
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('messages_pkey'))
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###
