"""change_column_id_to_user_id_in_users

Revision ID: 140e204e0142
Revises: 7781f1180a36
Create Date: 2025-12-28 20:18:24.676614

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "140e204e0142"
down_revision = '7781f1180a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        new_column_name="user_id",
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_id",
        new_column_name="id",
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###
