"""create_diaries

Revision ID: b70c8a3d488a
Revises: cbc4fb10711b
Create Date: 2025-12-31 14:59:04.776665

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b70c8a3d488a"
down_revision = 'cbc4fb10711b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaries',
    sa.Column('diary_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('diary_id')
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diaries')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
