"""update_chat_table

Revision ID: 2a81fbf9563b
Revises: 4bfbb3d030d5
Create Date: 2026-01-20 10:09:50.277221

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2a81fbf9563b"
down_revision = '4bfbb3d030d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.create_check_constraint(
        "check_rating_range",
        "chats",
        "rating >= 1 AND rating <= 10"
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'rating',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint("check_rating_range", "chats")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
