"""update_chat_table

Revision ID: 4bfbb3d030d5
Revises: b70c8a3d488a
Create Date: 2026-01-20 09:58:44.258366

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4bfbb3d030d5"
down_revision = 'b70c8a3d488a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'rating')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
